##### We are going to deal with image processing using numpy. we have got small image name smallgray.png. the size of this image is 15 pixels. 
##### via image processing we can recognize faces from images, videos and photos.
##### Python stores and read images using arrays of numbers.
##### 15 = 3*5 (3 list[ [],[],[]]) as we have 3 rows and 5 numbers in each list as columns. 

In [1]:
import numpy as np
import pandas as pd

In [2]:
n = np.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
#creading 2 dimensional array (9*3=27)
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
#creating a 3 dimensional array. this type of array used rarely.
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
# we can create a numpy list list out of python list
m = np.asarray([[123,234,456,651,321],[],[]])

In [8]:
m

array([list([123, 234, 456, 651, 321]), list([]), list([])], dtype=object)

In [9]:
print(m)

[list([123, 234, 456, 651, 321]) list([]) list([])]


In [10]:
# this is not a array
type(m)

numpy.ndarray

In [11]:
#OpenCV is an image processing library.Pandas dataframe are based on numpy arrays and openCV are also based on numpy arrays.
#pip install opencv-python
import cv2

In [12]:
#0 means you want to read the method in grayscale and 1 means u want to read the method in BGR(Blue Green Red)
img = cv2.imread("smallgray.png",0) 
#we will get 2D numpy array, it has 3*5
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
#when we want to pass the name of an image
cv2.imwrite("newsmallgray.png",img)

True

### Indexing, Slicing and iterating Numpy arrays


In [14]:
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
img.shape

(3, 5)

In [17]:
img[2,4]

182

In [18]:
for i in img:#(row-wise)
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [19]:
for i in img.T: #(columns)
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [20]:
#iterating value by value
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


### Stacking and Splitting numpy arrays

In [21]:
# for stacking there are two methods: hstack(horizontal stack) and the other is  vstack(vertical stack)
#concating arrays. We will put it in tuple()
ims = np.hstack((img,img))

In [22]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
imv = np.vstack((img,img))

In [24]:
print(imv)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [26]:
# splitting
lst=np.hsplit(ims,5) 
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [28]:
lsv = np.vsplit(imv,3) #vertical spli
lsv

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [29]:
type(lsv)

list

In [30]:
lsv[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)